sudo: false
language: rust

rust:
  - 1.31.0
  - stable
  - beta
  - nightly

script:
  - cargo check

matrix:
  include:
    - name: Clippy
      install:
        - CLIPPY_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)
        - echo "Latest nightly with Clippy is $CLIPPY_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$CLIPPY_NIGHTLY"
        - rustup component add clippy
      script:
        - cargo clippy --all-features -- -Dclippy::all
  allow_failures:
    - name: Clippy
  fast_finish: true
