[package]
name = "threadbound"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Make any value Sync but only available on its original thread."
repository = "https://github.com/dtolnay/threadbound"
documentation = "https://docs.rs/threadbound"
categories = ["rust-patterns"]
readme = "README.md"
